/*
 * Generated by gdbus-codegen 2.48.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "org.gnome.SettingsDaemon.Sharing.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.SettingsDaemon.Sharing
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GsdSharing
 * @title: GsdSharing
 * @short_description: Generated C code for the org.gnome.SettingsDaemon.Sharing D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gnome.SettingsDaemon.Sharing ---- */

static const _ExtendedGDBusArgInfo _gsd_sharing_method_info_enable_service_IN_ARG_service_name =
{
  {
    -1,
    (gchar *) "service_name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_sharing_method_info_enable_service_IN_ARG_pointers[] =
{
  &_gsd_sharing_method_info_enable_service_IN_ARG_service_name,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_sharing_method_info_enable_service =
{
  {
    -1,
    (gchar *) "EnableService",
    (GDBusArgInfo **) &_gsd_sharing_method_info_enable_service_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-enable-service",
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_sharing_method_info_disable_service_IN_ARG_service_name =
{
  {
    -1,
    (gchar *) "service_name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_sharing_method_info_disable_service_IN_ARG_network =
{
  {
    -1,
    (gchar *) "network",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_sharing_method_info_disable_service_IN_ARG_pointers[] =
{
  &_gsd_sharing_method_info_disable_service_IN_ARG_service_name,
  &_gsd_sharing_method_info_disable_service_IN_ARG_network,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_sharing_method_info_disable_service =
{
  {
    -1,
    (gchar *) "DisableService",
    (GDBusArgInfo **) &_gsd_sharing_method_info_disable_service_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-disable-service",
  FALSE
};

static const _ExtendedGDBusArgInfo _gsd_sharing_method_info_list_networks_IN_ARG_service_name =
{
  {
    -1,
    (gchar *) "service_name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_sharing_method_info_list_networks_IN_ARG_pointers[] =
{
  &_gsd_sharing_method_info_list_networks_IN_ARG_service_name,
  NULL
};

static const _ExtendedGDBusArgInfo _gsd_sharing_method_info_list_networks_OUT_ARG_networks =
{
  {
    -1,
    (gchar *) "networks",
    (gchar *) "a(sss)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gsd_sharing_method_info_list_networks_OUT_ARG_pointers[] =
{
  &_gsd_sharing_method_info_list_networks_OUT_ARG_networks,
  NULL
};

static const _ExtendedGDBusMethodInfo _gsd_sharing_method_info_list_networks =
{
  {
    -1,
    (gchar *) "ListNetworks",
    (GDBusArgInfo **) &_gsd_sharing_method_info_list_networks_IN_ARG_pointers,
    (GDBusArgInfo **) &_gsd_sharing_method_info_list_networks_OUT_ARG_pointers,
    NULL
  },
  "handle-list-networks",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _gsd_sharing_method_info_pointers[] =
{
  &_gsd_sharing_method_info_enable_service,
  &_gsd_sharing_method_info_disable_service,
  &_gsd_sharing_method_info_list_networks,
  NULL
};

static const _ExtendedGDBusPropertyInfo _gsd_sharing_property_info_current_network_name =
{
  {
    -1,
    (gchar *) "CurrentNetworkName",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "current-network-name",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gsd_sharing_property_info_current_network =
{
  {
    -1,
    (gchar *) "CurrentNetwork",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "current-network",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gsd_sharing_property_info_carrier_type =
{
  {
    -1,
    (gchar *) "CarrierType",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "carrier-type",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _gsd_sharing_property_info_sharing_status =
{
  {
    -1,
    (gchar *) "SharingStatus",
    (gchar *) "u",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "sharing-status",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _gsd_sharing_property_info_pointers[] =
{
  &_gsd_sharing_property_info_current_network_name,
  &_gsd_sharing_property_info_current_network,
  &_gsd_sharing_property_info_carrier_type,
  &_gsd_sharing_property_info_sharing_status,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gsd_sharing_interface_info =
{
  {
    -1,
    (gchar *) "org.gnome.SettingsDaemon.Sharing",
    (GDBusMethodInfo **) &_gsd_sharing_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_gsd_sharing_property_info_pointers,
    NULL
  },
  "sharing",
};


/**
 * gsd_sharing_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gsd_sharing_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct;
}

/**
 * gsd_sharing_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GsdSharing interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gsd_sharing_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "current-network-name");
  g_object_class_override_property (klass, property_id_begin++, "current-network");
  g_object_class_override_property (klass, property_id_begin++, "carrier-type");
  g_object_class_override_property (klass, property_id_begin++, "sharing-status");
  return property_id_begin - 1;
}



/**
 * GsdSharing:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link>.
 */

/**
 * GsdSharingIface:
 * @parent_iface: The parent interface.
 * @handle_disable_service: Handler for the #GsdSharing::handle-disable-service signal.
 * @handle_enable_service: Handler for the #GsdSharing::handle-enable-service signal.
 * @handle_list_networks: Handler for the #GsdSharing::handle-list-networks signal.
 * @get_carrier_type: Getter for the #GsdSharing:carrier-type property.
 * @get_current_network: Getter for the #GsdSharing:current-network property.
 * @get_current_network_name: Getter for the #GsdSharing:current-network-name property.
 * @get_sharing_status: Getter for the #GsdSharing:sharing-status property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link>.
 */

typedef GsdSharingIface GsdSharingInterface;
G_DEFINE_INTERFACE (GsdSharing, gsd_sharing, G_TYPE_OBJECT);

static void
gsd_sharing_default_init (GsdSharingIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * GsdSharing::handle-enable-service:
   * @object: A #GsdSharing.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_service_name: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.EnableService">EnableService()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_sharing_complete_enable_service() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-enable-service",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdSharingIface, handle_enable_service),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * GsdSharing::handle-disable-service:
   * @object: A #GsdSharing.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_service_name: Argument passed by remote caller.
   * @arg_network: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.DisableService">DisableService()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_sharing_complete_disable_service() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-disable-service",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdSharingIface, handle_disable_service),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * GsdSharing::handle-list-networks:
   * @object: A #GsdSharing.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_service_name: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.ListNetworks">ListNetworks()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gsd_sharing_complete_list_networks() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-list-networks",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GsdSharingIface, handle_list_networks),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject properties for D-Bus properties: */
  /**
   * GsdSharing:current-network-name:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetworkName">"CurrentNetworkName"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("current-network-name", "CurrentNetworkName", "CurrentNetworkName", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GsdSharing:current-network:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetwork">"CurrentNetwork"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("current-network", "CurrentNetwork", "CurrentNetwork", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GsdSharing:carrier-type:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CarrierType">"CarrierType"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("carrier-type", "CarrierType", "CarrierType", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GsdSharing:sharing-status:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.SharingStatus">"SharingStatus"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("sharing-status", "SharingStatus", "SharingStatus", 0, G_MAXUINT32, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * gsd_sharing_get_current_network_name: (skip)
 * @object: A #GsdSharing.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetworkName">"CurrentNetworkName"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gsd_sharing_dup_current_network_name() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gsd_sharing_get_current_network_name (GsdSharing *object)
{
  return GSD_SHARING_GET_IFACE (object)->get_current_network_name (object);
}

/**
 * gsd_sharing_dup_current_network_name: (skip)
 * @object: A #GsdSharing.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetworkName">"CurrentNetworkName"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gsd_sharing_dup_current_network_name (GsdSharing *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "current-network-name", &value, NULL);
  return value;
}

/**
 * gsd_sharing_set_current_network_name: (skip)
 * @object: A #GsdSharing.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetworkName">"CurrentNetworkName"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gsd_sharing_set_current_network_name (GsdSharing *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "current-network-name", value, NULL);
}

/**
 * gsd_sharing_get_current_network: (skip)
 * @object: A #GsdSharing.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetwork">"CurrentNetwork"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gsd_sharing_dup_current_network() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gsd_sharing_get_current_network (GsdSharing *object)
{
  return GSD_SHARING_GET_IFACE (object)->get_current_network (object);
}

/**
 * gsd_sharing_dup_current_network: (skip)
 * @object: A #GsdSharing.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetwork">"CurrentNetwork"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gsd_sharing_dup_current_network (GsdSharing *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "current-network", &value, NULL);
  return value;
}

/**
 * gsd_sharing_set_current_network: (skip)
 * @object: A #GsdSharing.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CurrentNetwork">"CurrentNetwork"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gsd_sharing_set_current_network (GsdSharing *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "current-network", value, NULL);
}

/**
 * gsd_sharing_get_carrier_type: (skip)
 * @object: A #GsdSharing.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CarrierType">"CarrierType"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gsd_sharing_dup_carrier_type() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
gsd_sharing_get_carrier_type (GsdSharing *object)
{
  return GSD_SHARING_GET_IFACE (object)->get_carrier_type (object);
}

/**
 * gsd_sharing_dup_carrier_type: (skip)
 * @object: A #GsdSharing.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CarrierType">"CarrierType"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
gsd_sharing_dup_carrier_type (GsdSharing *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "carrier-type", &value, NULL);
  return value;
}

/**
 * gsd_sharing_set_carrier_type: (skip)
 * @object: A #GsdSharing.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.CarrierType">"CarrierType"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gsd_sharing_set_carrier_type (GsdSharing *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "carrier-type", value, NULL);
}

/**
 * gsd_sharing_get_sharing_status: (skip)
 * @object: A #GsdSharing.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.SharingStatus">"SharingStatus"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint 
gsd_sharing_get_sharing_status (GsdSharing *object)
{
  return GSD_SHARING_GET_IFACE (object)->get_sharing_status (object);
}

/**
 * gsd_sharing_set_sharing_status: (skip)
 * @object: A #GsdSharing.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Sharing.SharingStatus">"SharingStatus"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gsd_sharing_set_sharing_status (GsdSharing *object, guint value)
{
  g_object_set (G_OBJECT (object), "sharing-status", value, NULL);
}

/**
 * gsd_sharing_call_enable_service:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.EnableService">EnableService()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_sharing_call_enable_service_finish() to get the result of the operation.
 *
 * See gsd_sharing_call_enable_service_sync() for the synchronous, blocking version of this method.
 */
void
gsd_sharing_call_enable_service (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "EnableService",
    g_variant_new ("(s)",
                   arg_service_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_sharing_call_enable_service_finish:
 * @proxy: A #GsdSharingProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_sharing_call_enable_service().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_sharing_call_enable_service().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_enable_service_finish (
    GsdSharing *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_call_enable_service_sync:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.EnableService">EnableService()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_sharing_call_enable_service() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_enable_service_sync (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "EnableService",
    g_variant_new ("(s)",
                   arg_service_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_call_disable_service:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @arg_network: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.DisableService">DisableService()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_sharing_call_disable_service_finish() to get the result of the operation.
 *
 * See gsd_sharing_call_disable_service_sync() for the synchronous, blocking version of this method.
 */
void
gsd_sharing_call_disable_service (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    const gchar *arg_network,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "DisableService",
    g_variant_new ("(ss)",
                   arg_service_name,
                   arg_network),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_sharing_call_disable_service_finish:
 * @proxy: A #GsdSharingProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_sharing_call_disable_service().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_sharing_call_disable_service().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_disable_service_finish (
    GsdSharing *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_call_disable_service_sync:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @arg_network: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.DisableService">DisableService()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_sharing_call_disable_service() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_disable_service_sync (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    const gchar *arg_network,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "DisableService",
    g_variant_new ("(ss)",
                   arg_service_name,
                   arg_network),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_call_list_networks:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.ListNetworks">ListNetworks()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_sharing_call_list_networks_finish() to get the result of the operation.
 *
 * See gsd_sharing_call_list_networks_sync() for the synchronous, blocking version of this method.
 */
void
gsd_sharing_call_list_networks (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ListNetworks",
    g_variant_new ("(s)",
                   arg_service_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gsd_sharing_call_list_networks_finish:
 * @proxy: A #GsdSharingProxy.
 * @out_networks: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_sharing_call_list_networks().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gsd_sharing_call_list_networks().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_list_networks_finish (
    GsdSharing *proxy,
    GVariant **out_networks,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sss))",
                 out_networks);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_call_list_networks_sync:
 * @proxy: A #GsdSharingProxy.
 * @arg_service_name: Argument to pass with the method invocation.
 * @out_networks: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.ListNetworks">ListNetworks()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gsd_sharing_call_list_networks() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
gsd_sharing_call_list_networks_sync (
    GsdSharing *proxy,
    const gchar *arg_service_name,
    GVariant **out_networks,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ListNetworks",
    g_variant_new ("(s)",
                   arg_service_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sss))",
                 out_networks);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gsd_sharing_complete_enable_service:
 * @object: A #GsdSharing.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.EnableService">EnableService()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_sharing_complete_enable_service (
    GsdSharing *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gsd_sharing_complete_disable_service:
 * @object: A #GsdSharing.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.DisableService">DisableService()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_sharing_complete_disable_service (
    GsdSharing *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * gsd_sharing_complete_list_networks:
 * @object: A #GsdSharing.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @networks: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-gnome-SettingsDaemon-Sharing.ListNetworks">ListNetworks()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gsd_sharing_complete_list_networks (
    GsdSharing *object,
    GDBusMethodInvocation *invocation,
    GVariant *networks)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(sss))",
                   networks));
}

/* ------------------------------------------------------------------------ */

/**
 * GsdSharingProxy:
 *
 * The #GsdSharingProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GsdSharingProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GsdSharingProxy.
 */

struct _GsdSharingProxyPrivate
{
  GData *qdata;
};

static void gsd_sharing_proxy_iface_init (GsdSharingIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GsdSharingProxy, gsd_sharing_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (GsdSharingProxy)
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SHARING, gsd_sharing_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (GsdSharingProxy, gsd_sharing_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SHARING, gsd_sharing_proxy_iface_init));

#endif
static void
gsd_sharing_proxy_finalize (GObject *object)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gsd_sharing_proxy_parent_class)->finalize (object);
}

static void
gsd_sharing_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _gsd_sharing_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
gsd_sharing_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.gnome.SettingsDaemon.Sharing: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
gsd_sharing_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  info = _gsd_sharing_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.gnome.SettingsDaemon.Sharing", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) gsd_sharing_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
gsd_sharing_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GSD_TYPE_SHARING);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GSD_TYPE_SHARING);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gsd_sharing_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
gsd_sharing_proxy_get_current_network_name (GsdSharing *object)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CurrentNetworkName");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gsd_sharing_proxy_get_current_network (GsdSharing *object)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CurrentNetwork");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
gsd_sharing_proxy_get_carrier_type (GsdSharing *object)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CarrierType");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static guint 
gsd_sharing_proxy_get_sharing_status (GsdSharing *object)
{
  GsdSharingProxy *proxy = GSD_SHARING_PROXY (object);
  GVariant *variant;
  guint value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "SharingStatus");
  if (variant != NULL)
    {
      value = g_variant_get_uint32 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
gsd_sharing_proxy_init (GsdSharingProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gsd_sharing_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GSD_TYPE_SHARING_PROXY, GsdSharingProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gsd_sharing_interface_info ());
}

static void
gsd_sharing_proxy_class_init (GsdSharingProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gsd_sharing_proxy_finalize;
  gobject_class->get_property = gsd_sharing_proxy_get_property;
  gobject_class->set_property = gsd_sharing_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gsd_sharing_proxy_g_signal;
  proxy_class->g_properties_changed = gsd_sharing_proxy_g_properties_changed;

  gsd_sharing_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GsdSharingProxyPrivate));
#endif
}

static void
gsd_sharing_proxy_iface_init (GsdSharingIface *iface)
{
  iface->get_current_network_name = gsd_sharing_proxy_get_current_network_name;
  iface->get_current_network = gsd_sharing_proxy_get_current_network;
  iface->get_carrier_type = gsd_sharing_proxy_get_carrier_type;
  iface->get_sharing_status = gsd_sharing_proxy_get_sharing_status;
}

/**
 * gsd_sharing_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_sharing_proxy_new_finish() to get the result of the operation.
 *
 * See gsd_sharing_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gsd_sharing_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GSD_TYPE_SHARING_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Sharing", NULL);
}

/**
 * gsd_sharing_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_sharing_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gsd_sharing_proxy_new().
 *
 * Returns: (transfer full) (type GsdSharingProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdSharing *
gsd_sharing_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GSD_SHARING (ret);
  else
    return NULL;
}

/**
 * gsd_sharing_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gsd_sharing_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GsdSharingProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdSharing *
gsd_sharing_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GSD_TYPE_SHARING_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Sharing", NULL);
  if (ret != NULL)
    return GSD_SHARING (ret);
  else
    return NULL;
}


/**
 * gsd_sharing_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gsd_sharing_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gsd_sharing_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gsd_sharing_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gsd_sharing_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GSD_TYPE_SHARING_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Sharing", NULL);
}

/**
 * gsd_sharing_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gsd_sharing_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gsd_sharing_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GsdSharingProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdSharing *
gsd_sharing_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GSD_SHARING (ret);
  else
    return NULL;
}

/**
 * gsd_sharing_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gsd_sharing_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gsd_sharing_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GsdSharingProxy): The constructed proxy object or %NULL if @error is set.
 */
GsdSharing *
gsd_sharing_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GSD_TYPE_SHARING_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Sharing", NULL);
  if (ret != NULL)
    return GSD_SHARING (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GsdSharingSkeleton:
 *
 * The #GsdSharingSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GsdSharingSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GsdSharingSkeleton.
 */

struct _GsdSharingSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gsd_sharing_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GSD_TYPE_SHARING);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GSD_TYPE_SHARING);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gsd_sharing_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gsd_sharing_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gsd_sharing_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gsd_sharing_skeleton_vtable =
{
  _gsd_sharing_skeleton_handle_method_call,
  _gsd_sharing_skeleton_handle_get_property,
  _gsd_sharing_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gsd_sharing_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gsd_sharing_interface_info ();
}

static GDBusInterfaceVTable *
gsd_sharing_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gsd_sharing_skeleton_vtable;
}

static GVariant *
gsd_sharing_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gsd_sharing_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gsd_sharing_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gsd_sharing_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gsd_sharing_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.SettingsDaemon.Sharing", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _gsd_sharing_emit_changed (gpointer user_data);

static void
gsd_sharing_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _gsd_sharing_emit_changed (skeleton);
}

static void gsd_sharing_skeleton_iface_init (GsdSharingIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GsdSharingSkeleton, gsd_sharing_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (GsdSharingSkeleton)
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SHARING, gsd_sharing_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (GsdSharingSkeleton, gsd_sharing_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GSD_TYPE_SHARING, gsd_sharing_skeleton_iface_init));

#endif
static void
gsd_sharing_skeleton_finalize (GObject *object)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  guint n;
  for (n = 0; n < 4; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gsd_sharing_skeleton_parent_class)->finalize (object);
}

static void
gsd_sharing_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_gsd_sharing_emit_changed (gpointer user_data)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.gnome.SettingsDaemon.Sharing",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_gsd_sharing_schedule_emit_changed (GsdSharingSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
gsd_sharing_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _gsd_sharing_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _gsd_sharing_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
gsd_sharing_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 4);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _gsd_sharing_schedule_emit_changed (skeleton, _gsd_sharing_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
gsd_sharing_skeleton_init (GsdSharingSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gsd_sharing_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GSD_TYPE_SHARING_SKELETON, GsdSharingSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 4);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_UINT);
}

static const gchar *
gsd_sharing_skeleton_get_current_network_name (GsdSharing *object)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gsd_sharing_skeleton_get_current_network (GsdSharing *object)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
gsd_sharing_skeleton_get_carrier_type (GsdSharing *object)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static guint 
gsd_sharing_skeleton_get_sharing_status (GsdSharing *object)
{
  GsdSharingSkeleton *skeleton = GSD_SHARING_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
gsd_sharing_skeleton_class_init (GsdSharingSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gsd_sharing_skeleton_finalize;
  gobject_class->get_property = gsd_sharing_skeleton_get_property;
  gobject_class->set_property = gsd_sharing_skeleton_set_property;
  gobject_class->notify       = gsd_sharing_skeleton_notify;


  gsd_sharing_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gsd_sharing_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gsd_sharing_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gsd_sharing_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gsd_sharing_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GsdSharingSkeletonPrivate));
#endif
}

static void
gsd_sharing_skeleton_iface_init (GsdSharingIface *iface)
{
  iface->get_current_network_name = gsd_sharing_skeleton_get_current_network_name;
  iface->get_current_network = gsd_sharing_skeleton_get_current_network;
  iface->get_carrier_type = gsd_sharing_skeleton_get_carrier_type;
  iface->get_sharing_status = gsd_sharing_skeleton_get_sharing_status;
}

/**
 * gsd_sharing_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Sharing.top_of_page">org.gnome.SettingsDaemon.Sharing</link>.
 *
 * Returns: (transfer full) (type GsdSharingSkeleton): The skeleton object.
 */
GsdSharing *
gsd_sharing_skeleton_new (void)
{
  return GSD_SHARING (g_object_new (GSD_TYPE_SHARING_SKELETON, NULL));
}

