debian/tmp/etc
debian/tmp/usr/share/gnome-control-center/xrdb/* etc/gnome/config/
debian/tmp/usr/share/gnome-control-center/glade
debian/tmp/usr/share/gnome-control-center/keybindings
debian/tmp/usr/share/gnome-control-center/pixmaps/
debian/tmp/usr/share/gnome-control-center/gnome-default-applications.xml
debian/tmp/usr/share/icons/hicolor
debian/tmp/usr/share/locale
debian/tmp/usr/share/mime/packages/gnome-theme-package.xml
debian/tmp/usr/share/gnome
debian/tmp/etc/gnome-vfs-2.0/modules
debian/tmp/etc/gconf/schemas
debian/tmp/usr/share/applications/*.desktop
debian/tmp/usr/share/omf
debian/tmp/usr/share/desktop-directories
debian/tmp/usr/share/dbus-1
