debian/tmp/etc/gconf
debian/tmp/etc/xdg/autostart
debian/tmp/etc/xdg/menus
debian/tmp/usr/share/gnome-control-center
debian/tmp/usr/share/gnome/help/control-center
debian/tmp/usr/share/sounds
debian/tmp/usr/share/desktop-directories
debian/tmp/usr/share/locale
debian/tmp/usr/share/icons
debian/tmp/usr/share/omf/
debian/visual-effects_custom.svg /usr/share/gnome-control-center/pixmaps
debian/visual-effects_extra.svg /usr/share/gnome-control-center/pixmaps
debian/visual-effects_none.svg /usr/share/gnome-control-center/pixmaps
debian/visual-effects_normal.svg /usr/share/gnome-control-center/pixmaps
