debian/tmp/etc
debian/tmp/usr/lib/bonobo/servers
debian/tmp/usr/share/control-center-2.0/xrdb/* etc/gnome/config/
debian/tmp/usr/share/control-center-2.0/interfaces
debian/tmp/usr/share/control-center-2.0/capplets
debian/tmp/usr/share/control-center-2.0/icons
debian/tmp/usr/share/control-center-2.0/pixmaps/
debian/tmp/usr/share/pixmaps/*.png
debian/tmp/usr/share/locale
debian/tmp/usr/share/gnome
debian/tmp/usr/share/applications
debian/tmp/usr/share/gnome-2.0
debian/tmp/usr/share/application-registry
debian/tmp/usr/share/mime-info
debian/tmp/usr/share/control-center-2.0
debian/tmp/usr/share/idl
debian/tmp/etc/gnome-vfs-2.0/modules
debian/tmp/etc/gconf/schemas
