.\" $Header: /aolnet/dev/src/CVS/sgml/docbook-to-man/cmd/docbook-to-man.sh,v 1.1.1.1 1998/11/13 21:31:59 db3l Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "gnome-control-center" "1" 
.SH "NAME" 
gnome-control-center \(em Desktop properties manager 
.SH "SYNOPSIS" 
.PP 
\fBgnome-control-center\fR [\fB-?, --help\fP]  [\fB--usage\fP]  [\fB--use-shell\fP]  [\fB--gdk-debug\fI=FLAGS\fR\fP]  [\fB--gdk-no-debug\fI=FLAGS\fR\fP]  [\fB--display\fI=DISPLAY\fR\fP]  [\fB--screen\fI=SCREEN\fR\fP]  [\fB--sync\fP]  [\fB--name\fI=NAME\fR\fP]  [\fB--class\fI=CLASS\fR\fP]  [\fB--gxid-host\fI=HOST\fR\fP]  [\fB--gxid-port\fI=PORT\fR\fP]  [\fB--gtk-debug\fI=FLAGS\fR\fP]  [\fB--gtk-no-debug\fI=FLAGS\fR\fP]  [\fB--g-fatal-warnings\fP]  [\fB--gtk-module\fI=MODULE\fR\fP]  [\fB--oaf-ior-fd\fI=FD\fR\fP]  [\fB--oaf-activate-iid\fI=IID\fR\fP]  [\fB--oaf-private\fP]  [\fB--disable-sound\fP]  [\fB--enable-sound\fP]  [\fB--espeaker\fI=HOSTNAME:PORT\fR\fP]  [\fB--version\fP]  [\fB--sm-client-id\fI=ID\fR\fP]  [\fB--sm-config-prefix\fI=PREFIX\fR\fP]  [\fB--sm-disable\fP]  [\fB--disable-crash-dialog\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBgnome-control-center\fR command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
Instead, it has documentation in the GNU       \fBInfo\fP format; see below. 
.PP 
\fBgnome-control-center\fR is a front-end to configuration applets (capplets) 
that lets you configure your GNOME desktop. You may set things such as the background,  
the fonts, or the theme 
.SH "SEE ALSO" 
.PP 
gtk-options (7). 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`-').  A summary of 
options is included below.  For a complete description, see the 
\fBInfo\fP files. 
.PP 
Theses options are mainly the standard command line options of gtk. 
.IP "\fB-?, --help\fP         " 10 
Show the help message. 
.IP "\fB--usage\fP         " 10 
Display brief usage message. 
.IP "\fB--use-shell\fP 	" 10 
Prevent Gnome Control Center from using Nautilus 
.IP "\fB--gdk-debug\fI=FLAGS\fR\fP 	" 10 
Enable Gdk debugging flags. 
.IP "\fB--gdk-no-debug\fI=FLAGS\fR\fP 	" 10 
Disable Gdk debugging flags. 
.IP "\fB--display\fI=DISPLAY\fR\fP 	" 10 
X display to use. 
.IP "\fB--screen\fI=SCREEN\fR\fP 	" 10 
X screen to use. 
.IP "\fB--sync\fP 	" 10 
Make X calls synchronous. 
.IP "\fB--name\fI=NAME\fR\fP 	" 10 
Program name as used by the window manager. 
.IP "\fB--class\fI=CLASS\fR\fP 	" 10 
Program class as used by the window manager 
.IP "\fB--gtk-debug\fI=FLAGS\fR\fP 	" 10 
Enable Gtk debugging flags. 
.IP "\fB--gtk-no-debug\fI=FLAGS\fR\fP 	" 10 
Disable Gtk debugging flags. 
.IP "\fB--g-fatal-warnings\fP 	" 10 
Make all warnings fatal 
.IP "\fB--gtk-module\fI=MODULE\fR\fP 	" 10 
Load an additional Gtk module. 
.IP "\fB--oaf-ior-fd\fI=FD\fR\fP 	" 10 
File descriptor to print IOR on 
.IP "\fB--oaf-activate-iid\fI=IID\fR\fP 	" 10 
IID to activate 
.IP "\fB--oaf-private\fP 	" 10 
Prevent registering of server with OAF 
.IP "\fB--disable-sound\fP 	" 10 
Disable sound server usage 
.IP "\fB--enable-sound\fP 	" 10 
Enable sound server usage 
.IP "\fB--espeaker\fI=HOSTNAME:PORT\fR\fP 	" 10 
Host:port on which the sound server to use is running 
.IP "\fB--version\fP 	" 10 
Show version. 
.IP "\fB--sm-client-id\fI=ID\fR\fP 	" 10 
Specify session management ID 
.IP "\fB--sm-config-prefix\fI=PREFIX\fR\fP 	" 10 
Specify prefix of saved configuration 
.IP "\fB--sm-disable\fP 	" 10 
Disable connection to session manager 
.IP "\fB--disable-crash-dialog\fP 	" 10 
Don't show crash dialog box. 
.SH "AUTHOR" 
.PP 
This manual page was written by Arnaud Patard arnaud.patard@rtp-net.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Sat 27 Mar 2004, 00:14 
