debian/tmp/etc/xdg/autostart
debian/tmp/etc/xdg/menus
debian/tmp/usr/share/gnome-control-center
debian/UbuntuLogo.png /usr/share/gnome-control-center/ui
debian/tmp/usr/share/gnome/help/control-center
debian/tmp/usr/share/sounds
debian/tmp/usr/share/desktop-directories
debian/tmp/usr/share/locale
debian/tmp/usr/share/icons
debian/tmp/usr/share/omf/
debian/tmp/usr/share/pixmaps
debian/source_gnome-control-center.py /usr/share/apport/package-hooks
